### ISSUE TITLE
pyaml output stringified inexplicably in places

### ISSUE THREAD

**Issue by paul-hammant** [mk-fg/pretty-yaml#22] opened 2017-04-26 23:53 UTC
```
from pyaml import dumps
with open("foobar.yaml", "w") as f2:
    x = {}
    x["y"] = []
    x["y"].append("0.5.1")
    x["y"].append("0.51")
    x["y"].append("0.7.1")
    print(dumps(x, safe=True, indent=1).decode('utf-8'), file=f2)
```

makes...

```
y:
- 0.5.1
- '0.51'
- 0.7.1
```
But it is not clear why one of the list entries is in quotes and the others not.

**Comment by mk-fg** [comment] 2017-04-27 04:48
It's happening because you're using "safe=True" there, which ensures that PyYAML's more robust serialization is used, and de-serialized data will be same as original, at the cost of some prettiness.

Reason why that one string is singled-out for escaping is simple - only `0.51` will be de-serialized as a number (0.51), while `0.5.1` and `0.7.1` will be interpreted as strings anyway (due to two dots in there), so no need for quotes there.

If you won't be passing safe=True, you should get desired output, but when de-serialized by any sane YAML parser, it will not match the original types, as mentioned.

Example:
```
% python3 -m pyaml <<< "{'y': ['0.5.1', '0.51', '0.7.1']}"
y:
  - 0.5.1
  - 0.51
  - 0.7.1

% python3 -c 'import yaml; print(yaml.safe_load("{y: [0.5.1, 0.51, 0.7.1]}"))'
{'y': ['0.5.1', 0.51, '0.7.1']}
```
Note missing quotes around 0.51 in the last output, indicating that it indeed was parsed as a float object instead of string.

It's an intended behavior that "unsafe" (default) serializer may produce such quirks (though hopefully not many), with human-readability preferred over correctness.
Same thing also mentioned in #20, I believe.

**Closed by mk-fg** 2017-04-27 04:48 UTC
